
# number of classes
nc: 20

# anchors
anchors:
  # [x1,y1, x2,y2, x3,y3]
  - [10,13, 16,30, 33,23]         # P3/8
  - [30,61, 62,45, 59,119]        # P4/16
  - [116,90, 156,198, 373,326]    # P5/32

backbone:
  # [from, repeat, module, args]
  - [-1, 1, Conv, [32, 3, 1]]  # 0
  - [-1, 1, Conv, [64, 3, 2]]  # 1-P1/2
  - [-1, 1, Block, [64]]
  - [-1, 1, Conv, [128, 3, 2]]  # 3-P2/4
  - [-1, 2, Block, [128]]
  - [-1, 1, Conv, [256, 3, 2]]  # 5-P3/8
  - [-1, 8, Block, [256]]
  - [-1, 1, Conv, [512, 3, 2]]  # 7-P4/16
  - [-1, 8, Block, [512]]
  - [-1, 1, Conv, [1024, 3, 2]]  # 9-P5/32
  - [-1, 4, Block, [1024]]  # 10

head:
  - [-1, 1, Block, [1024, False]]
  - [-1, 1, Conv, [512, 1, 1]]
  - [-1, 1, Conv, [1024, 3, 1]]
  - [-1, 1, Conv, [512, 1, 1]]
  - [-1, 1, Conv, [1024, 3, 1]]  # 15 (P5/32-large)

  - [-2, 1, Conv, [256, 1, 1]]
  - [-1, 1, Up, [None, 2, 'nearest']]
  - [[ -1, 8 ], 1, Concat, [1]]  # cat backbone P4
  - [-1, 1, Block, [512, False]]
  - [-1, 1, Block, [512, False]]
  - [-1, 1, Conv, [256, 1, 1]]
  - [-1, 1, Conv, [512, 3, 1]]  # 22 (P4/16-medium)

  - [-2, 1, Conv, [128, 1, 1]]
  - [-1, 1, Up, [None, 2, 'nearest']]
  - [[ -1, 6 ], 1, Concat, [1]]  # cat backbone P3
  - [-1, 1, Block, [256, False]]
  - [-1, 2, Block, [256, False]]  # 27 (P3/8-small)

  - [[ 27, 22, 15 ], 1, Out, []]   # Out(P3, P4, P5)


